<?php

namespace Automattic\WooCommerce\Blocks\BlockTypes;

/**
 * ProductQuery class.
 */
class ProductQuery extends \Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock
{
    /**
     * Block name.
     *
     * @var string
     */
    protected $block_name = 'product-query';
    /**
     * The Block with its attributes before it gets rendered
     *
     * @var array
     */
    protected $parsed_block;
    /**
     * Initialize this block type.
     *
     * - Hook into WP lifecycle.
     * - Register the block with WordPress.
     * - Hook into pre_render_block to update the query.
     */
    protected function initialize()
    {
    }
    /**
     * Check if a given block
     *
     * @param array $parsed_block The block being rendered.
     * @return boolean
     */
    private function is_woocommerce_variation($parsed_block)
    {
    }
    /**
     * Update the query for the product query block.
     *
     * @param string|null $pre_render   The pre-rendered content. Default null.
     * @param array       $parsed_block The block being rendered.
     */
    public function update_query($pre_render, $parsed_block)
    {
    }
    /**
     * Return a custom query based on attributes, filters and global WP_Query.
     *
     * @param WP_Query $query The WordPress Query.
     * @return array
     */
    public function build_query($query)
    {
    }
    /**
     * Return a query for on sale products.
     *
     * @return array
     */
    private function get_on_sale_products_query()
    {
    }
    /**
     * Set the query vars that are used by filter blocks.
     *
     * @param array $qvars Public query vars.
     * @return array
     */
    public function set_query_vars($qvars)
    {
    }
    /**
     * Return queries that are generated by query args
     *
     * @return array
     */
    private function get_queries_by_applied_filters()
    {
    }
    /**
     * Return queries that are generated by attributes
     *
     * @param array $parsed_block The Product Query that being rendered.
     * @return array
     */
    private function get_queries_by_attributes($parsed_block)
    {
    }
    /**
     * Return a query that filters products by price.
     *
     * @return array
     */
    private function get_filter_by_price_query()
    {
    }
}